name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --upgrade awscli
      
      - name: Use SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.YOUR_SECRET_PRIVATE_KEY }}

      - name: List SSH identities
        run: ssh-add -l
      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client


      - name: Deploy to EC2
        env:
          AWS_REGION: us-east-1

        run: |
          # Saving the private key to a file
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ env.AWS_REGION }}

          # Add your deployment commands here
          # Use scp command to copy cat.py to the EC2 instance
          scp -v -i $SSH_AUTH_SOCK cat.py ec2-user@ec2-54-167-45-44.compute-1.amazonaws.com:.
