name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Use the label of your self-hosted runner

    steps:

      - name: Run git pull on server
        run: |
            ssh -i ~/.ssh/id_rsa ec2-user@ec2-54-167-45-44.compute-1.amazonaws.com \
            "cd /home/ec2-user//cicdprod && git pull"
        
